FROM mysql:8.0
ENV MYSQL_ROOT_PASSWORD=ExpenseApp@1 \
    MYSQL_DATABASE=transactions \
    MYSQL_USER=expense \
    MYSQL_PASSWORD=ExpenseApp@1






   # FROM mysql:8.0
   # ENV MYSQL_ROOT_PASSWORD=ExpenseApp@1 \
      #  MYSQL_DATABASE=transactions \
      #  MYSQL_USER=expense \
       # MYSQL_PASSWORD=ExpenseApp@1
    #RUN groupadd expense \
     #   && useradd -g expense expense && \
      #  chown -R expense:expense /var/run/mysql /var/lib/mysqld 
    #USER expense 
    